### PR TITLE
Add problem solution

### PR DESCRIPTION
**Pull request by pinglu85**
add solution to problem 67. create your own promise

### CODE REVIEW

**Comment by BFEdev** [comment]
Thanks! Mind if you resolve the conflicts?

**Comment by pinglu85** [comment]
> Thanks! Mind if you resolve the conflicts?

I think I have resolved the conflicts.

**Comment by BFEdev** [comment]
Thank you!

**Comment by pinglu85** [comment]
I've noticed that BFE.dev doesn't render the youtube video widget, even though I have put the link in a separate line. Is it due to wrong format?

**Comment by BFEdev** [comment]
https://bigfrontend.dev/problem/create-your-own-Promise/solution

fixed. we don't support the shortened url though.

**Comment by pinglu85** [comment]
Thanks!

**Pull request merged**
